name:                contracts-open-games
version:             0.1.0.0
github:              "philipp-zahn/contracts-open-games"
license:             BSD3
author:              "Philipp Zahn"
maintainer:          "philipp.m.zahn@gmail.com"
copyright:           "Philipp Zahn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/philipp-zahn/contracs-algebra#readme>

dependencies:
  - base >= 4.7 && < 5
  - template-haskell
  - generic-random
  - open-games-hs
  - probability
  - splitmix
  - mwc-random
  - mtl
  - transformers
  - poly
  - profunctors
  - parsec
  - comonad
  - extra
  - fgl
  - graphviz
  - lens
  - typed-process
  - criterion
  - random



library:
  source-dirs: src
  exposed-modules:
    - Contracts.Subcontracting


executables:
  contracts-open-games-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - contracts-open-games

tests:
  equilibrium-test:
    buildable: True
    main:                SubcontractingEquilibrium
    source-dirs:         test
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - contracts-open-games 
      - template-haskell
      - base
      - hspec
      - QuickCheck
      - generic-random


